services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: composer install --no-dev
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: <your-app-key>
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: <your-database-host>
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: <your-database-name>
      - key: DB_USERNAME
        value: <your-database-username>
      - key: DB_PASSWORD
        value: <your-database-password>
