<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Monthly Maintenance Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 14px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        .table th, .table td {
            border: 1px solid #000;
            padding: 8px;
            text-align: left;
        }
        .table th {
            background-color: #f2f2f2;
        }
        .footer {
            text-align: center;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>KDSI House Management System</h1>
        <h3>Monthly Maintenance Report</h3>
        <p><strong>Date:</strong> {{ date('F Y') }}</p>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>House Name</th>
                <th>Maintenance Description</th>
                <th>Status</th>
                <th>Date Reported</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($maintenanceRequests as $request)
            <tr>
                <td>{{ $request->house->name }}</td>
                <td>{{ $request->description }}</td>
                <td>{{ ucfirst($request->status) }}</td>
                <td>{{ $request->created_at->format('d-m-Y') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    <div class="footer">
        <p>Generated by KDSI House Management System</p>
    </div>
</body>
</html>
